from __future__ import annotations

import asyncio
from typing import TYPE_CHECKING

from openai import AsyncOpenAI

if TYPE_CHECKING:
    from models import Class, DataProperty, ObjectProperty

INSTRUCTIONS = """You are given a WikiBase KG property or class and its typical connections. Produce a concise summary optimized for embeddings and vector search: define what it is, note key relationships, and use clear, retrieval-friendly terms. The summary should be a paragraph optimized for retrieval. If you encounter abbreviations, dont try to expand them, if not explicitly defined in your input. The goal is not to name relations, but given the relations, describe what they mean in a way that is easy to understand and use for retrieval."""

CLASS_TEMPLATE = """
Class: {name}
Description: {description}

Data properties:
{data_properties}
Object properties:
{object_properties}
"""

OBJECT_PROPERTY_TEMPLATE = """
Object property: {name}
Description: {description}

Common connections:
{connected_classes}
"""

DATA_PROPERTY_TEMPLATE = """
Data property: {name}
Description: {description}

Connected classes:
{connected_classes}
"""


async def augment_description(
    element: Class | ObjectProperty | DataProperty,
    client: AsyncOpenAI,
    model: str = "gpt-4o-mini",
    semaphore: asyncio.Semaphore | None = None,
) -> str:
    """Generate a retrieval-oriented summary for a schema entity.

    The summary text is intended for embedding/vector retrieval and complements
    the original `description` field.

    Args:
        element: Entity to summarize.
        client: OpenAI async client.
        model: OpenAI model used for generation.
        semaphore: Optional semaphore for limiting concurrent API requests

    Returns:
        Summary text generated by the model.

    Raises:
        ValueError: If `element` type is not supported.
    """

    from models import Class, DataProperty, ObjectProperty

    if isinstance(element, Class):
        input = _summarize_class(element)
    elif isinstance(element, ObjectProperty):
        input = _summarize_object_property(element)
    elif isinstance(element, DataProperty):
        input = _summarize_data_property(element)
    else:
        raise ValueError(f"Invalid element type: {type(element)}")

    async def _run_request() -> str:
        response = await client.responses.create(
            model=model,
            instructions=INSTRUCTIONS,
            input=input,
        )
        return response.output_text

    if semaphore is None:
        return await _run_request()

    async with semaphore:
        return await _run_request()


def _summarize_class(cls: Class) -> str:
    """Build the class prompt block sent to the LLM.

    Includes class metadata plus linked data/object properties.
    """
    assert cls.structure is not None, "Structure is not set"

    data_properties = []
    object_properties = []

    for data_property_id in cls.data_property_ids:
        data_property = cls.structure[data_property_id]
        data_properties.append(f"{data_property.label}: {data_property.description}")

    for object_property_id in cls.object_property_ids:
        object_property = cls.structure[object_property_id]
        object_properties.append(
            f"{object_property.label}: {object_property.description}"
        )

    return CLASS_TEMPLATE.format(
        name=cls.label,
        description=cls.description,
        data_properties="\n".join(data_properties or []),
        object_properties="\n".join(object_properties or []),
    )


def _summarize_object_property(op: ObjectProperty) -> str:
    """Build the object-property prompt block sent to the LLM.

    Includes property metadata and common class-to-class connections.
    """
    assert op.structure is not None, "Structure is not set"

    connected_classes = []

    for connection in op.common_connections:
        if connection.subject_id not in op.structure:
            continue
        if connection.object_id not in op.structure:
            continue

        subject = op.structure[connection.subject_id]
        object = op.structure[connection.object_id]
        connected_classes.append(f"{subject.label} -> {object.label}")

    return OBJECT_PROPERTY_TEMPLATE.format(
        name=op.label,
        description=op.description,
        connected_classes="\n".join(connected_classes or []),
    )


def _summarize_data_property(dp: DataProperty) -> str:
    """Build the data-property prompt block sent to the LLM.

    Includes property metadata and linked classes.
    """
    assert dp.structure is not None, "Structure is not set"

    connected_classes = []

    for class_id in dp.class_ids:
        class_ = dp.structure[class_id]
        connected_classes.append(class_.label)

    return DATA_PROPERTY_TEMPLATE.format(
        name=dp.label,
        description=dp.description,
        connected_classes="\n".join(connected_classes or []),
    )
